name=postgres-events-connector
connector.class=io.debezium.connector.postgresql.PostgresConnector

# Postgres connection
database.hostname=localhost
database.port=5432
database.user=debezium_user
database.password=debezium_pass
database.dbname=postgres

# Replication slot & publication
slot.name=debezium_slot
publication.name=debezium_pub
plugin.name=pgoutput

# Tables to capture
table.include.list=public.events

# Kafka topic prefix
topic.prefix=dbserver

database.server.name=dbserver   # just a logical name you choose for Debezium.It is used only by Debezium, not by Postgres.
database.history.kafka.bootstrap.servers=localhost:9092
database.history.kafka.topic=dbhistory.postgres

